CREATE TABLE YURIPJ.MEMBER
(
  ID    VARCHAR2(30 BYTE) NOT NULL,
  PW    VARCHAR2(10 BYTE) NOT NULL,
  NICKNAME  VARCHAR2(20 BYTE) NOT NULL,
  ONOFF   VARCHAR2(10 BYTE) NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX YURIPJ.MEMBER_ID_PK ON YURIPJ.MEMBER
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE YURIPJ.MEMBER ADD (
  CONSTRAINT MEMBER_ID_PK
  PRIMARY KEY
  (ID)
  USING INDEX YURIPJ.MEMBER_ID_PK
  ENABLE VALIDATE);
