CREATE TABLE PRIVATECHAT(
    PVT_ROOM VARCHAR2(10 BYTE) NOT NULL,
    PVT_MSG VARCHAR2(1000 BYTE) NOT NULL
    )
    
CREATE UNIQUE INDEX YURIPJ.PVT_ROOM_PK ON YURIPJ.PRIVATECHAT
(PVT_ROOM)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE YURIPJ.PRIVATECHAT ADD (
  CONSTRAINT PVT_ROOM_PK
  PRIMARY KEY
  (PVT_ROOM)
  USING INDEX YURIPJ.PVT_ROOM_PK
  ENABLE VALIDATE);